services:
  pytrichmots:
    image: pytrichmots:latest
    build: .
    container_name: pytrichmots-api
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 5000:80
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 30s
