services:
  pytrichmots:
    build: .
    container_name: pytrichmots-api
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 5000:80
    volumes:
      - .:/app
